trigger:
  - master
  - main

pr: none

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: John D Watson
    name: johnwatson484/azure-devops-templates

extends:
  template: build.yaml@templates
  parameters:
    repo: lynx-magnus-web
    containerRepository: johnwatson484/lynx-magnus-web
    helmChartPath: helm/lynx-magnus-web
    