version: '3'
services:
  lynx-magnus:
    build: .
    image: lynx-magnus
    container_name: lynx-magnus
    command: npm run start:watch
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
