version: '3.7'
services:
  lynx-magnus:   
    environment:
      NODE_ENV: development 
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    command: npm run start:watch

volumes:
  node_modules:
