version: '3.7'
services:
  lynx-magnus:   
    environment:
      NODE_ENV: development 
    volumes:
      - ./server/:/usr/src/app/server/
      - ./index.js:/usr/src/app/index.js
      - ./package.json:/usr/src/app/package.json
    command: npm run start:watch
