version: '3.8'
services:
  lynx-magnus:
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./app:/node/app
      - ./package.json:/node/package.json
