environment: development
name: lynx-magnus-web
image: lynx-magnus-web

service:
  port: 80

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 20Mi
  requestCpu: 20m
  limitMemory: 20Mi
  limitCpu: 20m
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  port: 3000

ingress:
  class: nginx
  host:
  certIssuer: letsencrypt

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000
