environment: development
name: lynx-magnus-web
image: lynx-magnus-web

service:
  port: 80

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 60Mi
  limitCpu: 60m
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  port: 3000
  skywalkingCollectorAddress: http://skywalking-oap.skywalking.svc.cluster.local:11800

ingress:
  class: nginx
  host:
  certIssuer: letsencrypt

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000
