{{- include "helm-library.configmap" (list . "lynx-magnus-web.configmap") -}}
{{- define "lynx-magnus-web.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  SKYWALKING_SERVICE_NAME: {{ quote .Values.name}}
  {{- if .Values.container.skywalkingCollectorAddress }}
  SKYWALKING_COLLECTOR_ADDRESS: {{ quote .Values.container.skywalkingCollectorAddress }}
  {{- end }}
{{- end -}}
