{{- include "helm-library.configmap" (list . "lynx-magnus-web.configmap") -}}
{{- define "lynx-magnus-web.configmap" -}}
data:
  NODE_ENV: {{ .Values.configMap.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
{{- end -}}
